name: Issue a Google certificate
on:
  workflow_dispatch:
  push:
    branches: master
    paths:
      - ".github/workflows/certificate.yml"
env:
  Ali_Key: ${{ secrets.Ali_Key }}
  Ali_Secret: ${{ secrets.Ali_Secret }}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Install acme.sh
        run: |
          curl https://get.acme.sh | sh
        shell: bash
      - name: Emit certificate
        run: |      
          ~/.acme.sh/acme.sh --register-account -m ${{ secrets.ACME_EMAIL }} --server google --eab-kid 660f7aa66f86ab9876811f0399b75ca1 --eab-hmac-key lKV860_rF6DnU8SZG__Fa0HGLk24EaV405obqt1qsJQtgwfKnGsh5ry6CCyyDmePeCYkT42-b4fO605u4ilaNg
          ~/.acme.sh/acme.sh --issue --server google -d frenchvandal.cn -d www.frenchvandal.cn  --dns dns_ali
        shell: bash
      - name: Upload certificate
        uses: actions/upload-artifact@v3
        with:
         name: certificate
         path: |
           /home/runner/.acme.sh/
