name: Issue a Google certificate
on:
  workflow_dispatch:
  push:
    branches: master
    paths:
      - "content/**"
      - "layouts/**"
      - "static/**"
      - "themes/**"
      - ".github/workflows/certificate.yml"
      - "config.yaml"

env:
  Ali_Key: ${{ secrets.Ali_Key }}
  Ali_Secret: ${{ secrets.Ali_Secret }}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Install acme.sh
        run: |
          curl https://get.acme.sh | sh
        shell: bash
      - name: Emit certificate
        run: |      
          ~/.acme.sh/acme.sh  --register-account -m ${{ secrets.ACME_EMAIL }} --server google --eab-kid ${{ secrets.EAB_KID }} --eab-hmac-key ${{ secrets.EAB_HMAC_KEY }}
          ~/.acme.sh/acme.sh --issue --server google -d frenchvandal.cn -d www.frenchvandal.cn  --dns dns_ali --debug
        shell: bash
      - name: Upload certificate
        uses: actions/upload-artifact@v3
        with:
         name: certificate
         path: |
           /home/runner/.acme.sh/

