name: Issue a Google certificate
on:
  workflow_dispatch:
  push:
    branches: master
    paths:
      - ".github/workflows/certificate.yml"
env:
  Ali_Key: ${{ secrets.Ali_Key }}
  Ali_Secret: ${{ secrets.Ali_Secret }}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Install acme.sh
        run: |
          curl https://get.acme.sh | sh
        shell: bash
      - name: Emit certificate
        run: |      
          ~/.acme.sh/acme.sh --register-account -m philippe.ribeiro@gmail.com --server google --eab-kid 77314e6fd9c3e9029a4e0648ee2cbf9c --eab-hmac-key jSI947WSKnDGKkgxyyoeb20ekZvcKHSCDK5sQmi79GF8jDd8bzjCylotVlURGtcDXdLLRS9VqwbE7AYX3VtPsQ
          ~/.acme.sh/acme.sh --issue --server google -d frenchvandal.cn -d www.frenchvandal.cn --dns dns_ali
        shell: bash
      - name: Upload certificate
        uses: actions/upload-artifact@v4
        with:
         name: certificate
         path: |
           /home/runner/.acme.sh/
