name: Deploy Hugo on Aliyun OSS
on:
  workflow_dispatch:
  push:
    branches: master
    paths:
      - "content/**"
      - "layouts/**"
      - "static/**"
      - "themes/**"
      - ".github/workflows/deployment.yml"
      - "config.yaml"
permissions:
  id-token: write
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set-up Node
        uses: actions/setup-node@v4.0.3
        with:
          node-version: "20"
      - name: Cache node modules
        uses: actions/cache@v4.1.0
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Dependencies
        run: |
          node -v
          npm install
          npm -v
      - name: Install & Run Hugo
        uses: frenchvandal/action-hugo@master
        with:
          version: latest
          extended: true
          args: --cleanDestinationDir --enableGitInfo
      - name: hugo version
        run: hugo version
      - name: configure Aliyun CLI
        run: |
          aliyun configure set \
          --profile default \
          --mode AK \
          --region ${{ secrets.OSS_REGION }} \
          --access-key-id ${{ secrets.OSS_ACCESS_KEY_ID }} \
          --access-key-secret ${{ secrets.OSS_ACCESS_KEY_SECRET }}
      - name: Upload to OSS bucket
        uses: frenchvandal/action-oss-upload@master
        with:
          bucket: ${{ secrets.OSS_BUCKET }}
          region: ${{ secrets.OSS_REGION }}
          accessKeyId: ${{ secrets.OSS_ACCESS_KEY_ID }}
          accessKeySecret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
          source: public
