name: Deploy Hugo on Aliyun OSS
on:
  workflow_dispatch:
  push:
    branches: master
    paths:
      - "content/**"
      - "layouts/**"
      - "static/**"
      - "themes/**"
      - ".github/workflows/deployment.yml"
      - "config.yaml"
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set-up Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Dependencies
        run: npm install
      - name: Install & Run Hugo
        uses: frenchvandal/action-hugo@master
        with:
          version: latest
          extended: false
          args: --cleanDestinationDir --enableGitInfo
      - name: inline critical CSS
        run: node critical.js
      - name: Upload to OSS bucket
        uses: frenchvandal/action-oss-upload@master
        with:
          bucket: ${{ secrets.OSS_BUCKET }}
          region: ${{ secrets.OSS_REGION }}
          accessKeyId: ${{ secrets.OSS_ACCESS_KEY_ID }}
          accessKeySecret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
          source: public

