name: Deploy Hugo on Aliyun OSS
on:
  workflow_dispatch:
  push:
    branches: master
    paths:
      - "content/**"
      - "layouts/**"
      - "static/**"
      - "themes/**"
      - ".github/workflows/deployment.yml"
      - "config.yaml"
permissions:
  id-token: write
  contents: read
jobs:
  build:
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install & Run Hugo
        uses: frenchvandal/action-hugo@master
        with:
          version: latest
          extended: true
        env:
          ALIBABA_CLOUD_ROLE_ARN: ${{ secrets.ALIBABA_CLOUD_ROLE_ARN }}
          ALIBABA_CLOUD_OIDC_PROVIDER_ARN: ${{ secrets.ALIBABA_CLOUD_OIDC_PROVIDER_ARN }}

